version: '0.0'

services:

  frontend:
    build:
      context: ./Frontend
      args: 
        VITE_API_URL: http://192.168.1.16
    ports: 
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    ports: 
      - "3000:3000"
    depends_on: 
      - mongo

  mongo:
    image: mongo:latest
    ports: 
      - "27017:27017"
