services:
  frontend:
    container_name: react-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=http://backend:3000
    ports:
      - "80:80"
    environment:
      - VITE_BACKEND_URL=http://backend:3000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    container_name: express-backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27016/
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    container_name: mongo_container
    image: mongo:latest
    ports:
      - "27016:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
